-- Las tablas NO están creadas. En la diapo 26 se especifican como deben ser las tablas

-- Asegurarse que las tablas no están
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_PEDIDO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PEDIDO CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STOCK CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- Crearlas (FBD)
CREATE TABLE STOCK(
  CPRODUCTO NUMBER(10)    PRIMARY KEY,
  CANTIDAD  NUMBER(10)    NOT NULL CHECK (CANTIDAD >= 0)
);

CREATE TABLE PEDIDO(
  CPEDIDO       NUMBER(10) PRIMARY KEY,
  CCLIENTE      NUMBER(10) NOT NULL,
  FECHA_PEDIDO  DATE       NOT NULL
);

CREATE TABLE DETALLE_PEDIDO(
  CPEDIDO    NUMBER(10) NOT NULL,
  CPRODUCTO  NUMBER(10) NOT NULL,
  CANTIDAD   NUMBER(10) NOT NULL CHECK (CANTIDAD > 0),
  CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (CPEDIDO, CPRODUCTO),
  CONSTRAINT FK_DP_PEDIDO FOREIGN KEY (CPEDIDO)   REFERENCES PEDIDO(CPEDIDO)   ON DELETE CASCADE,
  CONSTRAINT FK_DP_STOCK  FOREIGN KEY (CPRODUCTO) REFERENCES STOCK(CPRODUCTO)
);

--Comprobar que todo ok

SELECT table_name FROM user_tables
WHERE table_name IN ('STOCK','PEDIDO','DETALLE_PEDIDO');

SELECT table_name, column_name, data_type, data_length
FROM user_tab_columns
WHERE table_name IN ('STOCK','PEDIDO','DETALLE_PEDIDO')
ORDER BY table_name, column_id;
